app: 
  port: 6233
  docs: true
  logging: true # for logging stuffs out
  morgan: false # for request logging
  jwt:
    SecretKey: lovemelikeyoudo
    accessTokenExpiryTime: 7d

database:
  url: mongodb://localhost:27017/miwago_test

docsUrl: "localhost:7000"

mails:
  enable: true
  defaultFrom: miwago@cubettech.com # this is the source email that is used to send emails(from address)
  admin: 'aumadmin@yopmail.com'
  errMails: miwago-bug-report@cubettech.com

issue-maker:
  service: gitlab
  projectId: 938
  endPoint: http://117.247.186.100:9898
  privateToken: QtHVSf1hvAeCqd6Bu7-X

frontEnd:
  web:
    baseUrl: 'http://localhost:7011'
  admin:
    baseUrl: 'http://localhost:7012'

AWS_BUCKET_NAME: miwagoassets