app: 
  port: 6233
  docs: true
  logging: true # for logging stuffs out
  morgan: true # for request logging
  jwt:
    SecretKey: lovemelikeyoudo
    accessTokenExpiryTime: 7d

database:
  url: mongodb://localhost:27017/miwago_test

mails:
  enable: false
  defaultFrom: miwago@cubettech.com # this is the source email that is used to send emails(from address)
  admin: 'aumadmin@yopmail.com'
  errMails: vajahath.ahmed@cubettech.com

frontEnd:
  web:
    baseUrl: 'http://localhost:7011'
  admin:
    baseUrl: 'http://localhost:7012'

AWS_BUCKET_NAME: miwago-assets