app: 
  port: 4000
  docs: true
  logging: true # for logging stuffs out
  morgan: true # for request logging
  jwt:
    SecretKey: lovemelikeyoudo
    accessTokenExpiryTime: 7d

database:
  url: mongodb://localhost/miwago

mails:
  enable: false
  admin: 'aumadmin@yopmail.com'
  errMails: vajahath.ahmed@cubettech.com

frontEnd:
  web:
    baseUrl: 'http://localhost:7011'
  admin:
    baseUrl: 'http://localhost:7012'