# STAGING
# This is given for client for their testing purposes

app:
  logging: false
  morgan: false
  port: 6233
  docs: false

database:
  url: mongodb://miwago_user:B34M6544VfsD4355sdftsdf54sdfgGChjuuhmjvhmr423574rcvc@192.168.200.10:27017/miwago_db
