# STAGING
# This is given for client for their testing purposes

app:
  logging: false
  morgan: false
  port: 6233
  docs: false

database:
  url: mongodb://miwago_user:NBGVJHgjhg67uhgvjuuy5hjnv98jkhbBGbkjbhfgjhbkmjhb76hjv98bkjbnjmn@192.168.200.20:27017/miwago_db_staging
