# ORIGINAL PRODUCTION
# configuration for production server (live)

app:
  logging: true
  morgan: true
  port: 3000
  docs: false

database:
  url: 'mongodb://miwago_user:NBGVJHgjhg67uhgvjuuy5hjnv98jkhbBGbkjbhfgjhbkmjhb76hjv98bkjbnjmn@185.148.147.8:27018/miwago_db'