# ORIGINAL PRODUCTION
# configuration for production server (live)

app:
  logging: true
  morgan: true
  port: 3000
  docs: false

database:
  url: 'mongodb+srv://capricorns-db-user:Capricorns-DB-pwd-56$@capricons-cl1-jngps.mongodb.net/miwago_db?retryWrites=true'